# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-03 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
